### PR TITLE
Refactors the detectors to be properties

### LINKED ISSUE #74: Array vs. 15 named properties?
https://github.com/nasa-gcn/gcn-schema/blob/fcf288bd8c418c915f291492f452d44e10648be4/gcn/notices/glowbug/alert.example.json#LL24C1-L39C1

Hi,

What was the reason to change the array of 15 with 15 named properties? 

In the current schema the names can be anything? Shouldn't we change that?

Thanks!

### PR DESCRIPTION
**Pull request by dakota002**
Closes #74

### CODE REVIEW

**Comment by dakota002** [comment]
@shb46 is this what you had in mind for separating out each detector?

**Comment by shb46** [comment]
@dakota002: Yes. Except that I didn't mean to make anything required.

**Comment by dakota002** [comment]
No problem, I can remove the required part

**Comment by shb46** [comment]
@dakota002: Thanks!

**Comment by Vidushi-GitHub** [comment]
@shb46 for both human-reading and data-base prospects writing each detector status as separate field (would appear as separate 15 columns table for Glowbug only) doesn't seem convenient way. I had a chat with @jracusin, we would prefer to see it as a single field type. Like Fermi also report as single field such as detector="00001001110". Is it fine if we go with previous way, detector status  = {CsI0=on, CsI1=off...etc}? @dakota002

**Comment by shb46** [comment]
@Vidushi-GitHub (CC: @dakota002, @jracusin, @lpsinger): Either way is ok, since it is the same information presented in a slightly different way. Correct me if I'm wrong, but are you proposing a string, as in:

> `"detector_status":"CsI0=on, CsI1=off,`...`,SAA=on}"`.

It is more concise and easily parsable, for those who need these data. At the very beginning I was thinking of using the Fermi-GBM style. Enhanced to show 3-states per detector, it could look like:

> `"detector_status":"1111 1211 0111 00 1"`

Also, a reminder that an array of 15 string enums was one of the previous suggestions:

> `"detector_status":["on","on","on","on","on","triggered","on","on","off","on","on","on","off","off","on"]`

Since you know best what you need for a best GCN system, please pick and tweak and keep me posted.

**Pull request merged**
